fitblog/config/routes.rb
Fitblog::Application.routes.draw do
  get "about/index"
  get "about", to: "about#index"
  get "dashboard/index"
  get "dashboard", to: "dashboard#index"
  get "posts/index"
  get "posts", to: "posts#index"
  

  root 'posts#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :destroy]
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  

end

fitblog/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

fitblog/app/models/post.rb
class Post < ActiveRecord::Base
	validates :body, presence: true
	has_many :comments, dependent: :destroy
	paginates_per 5
end

fitblog/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/, on: :create
  has_many :comments
end

fitblog/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

fitblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  helper_method :user_signed_in?
  
  # prevent from being used as actions on other contollers (called by paths/routes)
  private
  
    def current_user
      User.find(session[:user_id]) if session[:user_id]
    end
  
    def user_signed_in?
      current_user.present?
    end
  
    def require_authentication
      if current_user.nil?
        redirect_to new_session_url
      end
    end

    def fitbit_client
      Fitgem::Client.new({:consumer_key => 'abc123', :consumer_secret => 'def456', :token => 'pqr161718', :secret => 'stu192021'})
    end
end

fitblog/app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  
  end
end

fitblog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
    
    user_id = User.find(session[:user_id]).id

    # @comment = @post.comments.create(params[:comment].permit(:text))
    @comment = @post.comments.new
    @comment.post_id = params[:post_id]
    @comment.user_id = user_id
    @comment.text = params[:comment][:text]
    @comment.save
    redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

	def comment_params
		# TODO: how to do strong parameters in this case?
	end
end

fitblog/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_authentication
  
  def index
  	@badges = fitbit_client.badges['badges']
  end
end

fitblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ActionView::Helpers::NumberHelper

  before_action :require_authentication
  skip_before_action :require_authentication, only: [:index, :show]

  def index
    @posts = Post.all.order('post_date DESC').page params[:page]
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.where(post_id: params[:id]).order('created_at DESC')

    temp_steps = fitbit_client.data_by_time_range("/activities/tracker/steps", {:base_date => "#{@post.post_date}", :period => "1d"})['activities-tracker-steps'][0]['value']
    @steps = number_with_delimiter(temp_steps)

    temp_total_minutes = fitbit_client.sleep_on_date(@post.post_date)['sleep'][0]['minutesAsleep'].to_i
    temp_hours = temp_total_minutes/60
    temp_minutes = temp_total_minutes % 60
    @sleep = temp_hours.to_s + 'h ' + temp_minutes.to_s + 'm'
  end
  
  def new
  	@post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = 'Post saved.'
      redirect_to root_url
    end
  end

  def update
    @post = Post.find(params[:id])
    #@post.title = params(post[:title])
    #@post.body = params(post[:body])
    if @post.update(post_params)
      flash[:notice] = 'Post updated.'
      redirect_to root_url
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = 'Post deleted.'
      redirect_to root_url
    end
  end
  
  private_class_method
    def post_params
      params.require(:post).permit(:title, :post_date, :body)
    end
end

fitblog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  	
  end
  
  def create
    @user = User.find_by(email: params[:email])
  	
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash[:alert] = "Invalid email or password supplied."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  
end

fitblog/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  
  def create
  	@user = User.new(user_params)
    @user.is_admin = 0;
  	if @user.save
      redirect_to root_path
  	end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = 'User deleted.'
      render 'index'
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

fitblog/app/helpers/about_helper.rb
module AboutHelper
end

fitblog/app/helpers/application_helper.rb
module ApplicationHelper
end

fitblog/app/helpers/blog_helper.rb
module BlogHelper
end

fitblog/app/helpers/comments_helper.rb
module CommentsHelper
end

fitblog/app/helpers/dashboard_helper.rb
module DashboardHelper
end

fitblog/app/helpers/posts_helper.rb
module PostsHelper
end

fitblog/app/helpers/sessions_helper.rb
module SessionsHelper
end

fitblog/app/helpers/users_helper.rb
module UsersHelper
end

fitblog/app/views/about/index.html.erb
<article>
	<h2>About</h2>
	<p>This Ruby on Rails blog application was built as an exploration into the various aspects of building in Rails, and to satisfy the final project requirements of the CodeFellows Evening Rails Class.</p>

	<p>The blog simply consists of once-daily posts that document my general level of activity and mood during the day. When read on the detail/show page, the daily step count and previous night's sleep totals are listed along with the blog post.</p>

	<p>You can sign up to be a user so that you can create comments for each post on the detail/show page. The primary user (me!) is marked as an admin so that I can update posts, delete them or delete comments.</p>
</article>

fitblog/app/views/blog/index.html.erb
<h1>FitBlog</h1>

<!-- in sidebar or header -->
<% if user_signed_in? %>
  Hello, <%= current_user.name %>.<br>
  <%= link_to 'Sign out', session_path(session[:user_id]), method: :delete %>
<% else %>
  You are not signed in.<br>
<%= link_to 'Sign in', new_session_path %>
<% end %>

fitblog/app/views/dashboard/index.html.erb
<article>

<h2>Dashboard</h2>

<p><h4>Badges</h4></p>

<% @badges.each do |badge| %>
	<img src='<%= badge['image50px'] %>' /> achieved <%= pluralize(badge['timesAchieved'], 'time') %><br>
<% end %>

</article>

fitblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FitBit Blog (on Rails)</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
		<header>
			<div id="masthead">
				<h1>FitBit Blog</h1>
				(On Rails)
			</div>
			<nav>
				<ul>
					<li><%= link_to 'Posts', root_path %></li>
					<li><%= link_to 'Dashboard', dashboard_path %></li>
					<li><%= link_to 'About', about_path %></li>
				</ul>
			</nav>
			<div id="cubes">
				<div class="cube">
				walk
				</div><!--
				--><div class="cube">
				run
				</div><!--
				--><div class="cube">
				work
				</div><!--
				--><div class="cube">
				play
				</div>
			</div>
		</header>
		<div id="content">
			<div id="articles">

				<%= yield %>

			</div>
			<aside>
				<div id="loggedIn">
					<% if user_signed_in? %>
					  <p>Hello, <%= current_user.name %>.</p>
					  <p><% if current_user.is_admin %><%= link_to 'Create a new post?', new_post_path %><% end %></p>
					  <p><%= link_to 'Sign out', session_path(session[:user_id]), method: :delete %></p>
					<% else %>
						<%= link_to 'Sign in', new_session_path %>
					<% end %>
				</div>

				<h3>Tags</h3>
				<ul>
					<li><a href="#">Tag 1</a></li>
					<li><a href="#">Tag 2</a></li>
					<li><a href="#">Tag 3</a></li>
				</ul>

				<h3>Recent Posts</h3>
				<ul>
					<li><a href="#">July</a></li>
					<li><a href="#">August</a></li>
					<li><a href="#">September</a></li>
				</ul>
			</aside>
		</div>
		<footer>
			&copy 2013 Cylinder Studio
		</footer>
	</div>

</body>
</html>

fitblog/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<%= pluralize(@post.errors.count, "error") %> prohibited the post from being saved:
		<ul>
		<% @post.errors.each do |error| %>
			<li><%= error %></li>
		<% end %>
		</ul>
	<% end %>
	<p><%= f.label :title %><br><%= f.text_field :title, class: '' %></p>
	<p><%= f.label :post_date %><br><%= f.date_select :post_date %></p>
	<p><%= f.label :body %><br><%= f.text_area :body %></p>
	<%= f.submit %>
<% end %>

fitblog/app/views/posts/edit.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>

<%= render 'form' %>

fitblog/app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<article>
		<h2><a href="<%= post_path(post.id) %>"><%= post.title %></a></h2>
		<div class="timestamp">
			<time datetime="<%= post.post_date %>"><%= Date::MONTHNAMES[post.post_date.month] %> <%= post.post_date.day %>, <%= post.post_date.year %></time>
		</div>
		<p><%= post.body %></p>
		<p><a href="<%= post_path(post.id) %>">See more ></a></p>
		<% if user_signed_in? && current_user.is_admin %>
		<p>
			<%= link_to "Edit post", edit_post_path(post) %> |
			<%= link_to "Delete post", post_path(post), method: :delete, data: {confirm: 'Sure about that?'} %>
		</p>
		<% end %>
	</article>
<% end %>		

<%= paginate @posts %>

fitblog/app/views/posts/new.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>

<%= render 'form' %>

fitblog/app/views/posts/show.html.erb
<article>
	<h2><%= @post.title %></h2>
	<div class="timestamp">
		<time datetime="<%= @post.post_date %>"><%= Date::MONTHNAMES[@post.post_date.month] %> <%= @post.post_date.day %>, <%= @post.post_date.year %></time>
	</div>
	<p><%= @post.body %></p>
	<% if @steps && @sleep %>
		<p>Fitbit steps reported: <%= @steps %> steps</p>
		<p>Fitbit sleep reported: <%= @sleep %></p>
	<% end %>
</article>

<p class="linkText"><%= link_to 'Back to Posts >', posts_path %></p>

<% if user_signed_in? %>
	<p>Enter comment:<br>
	<%= form_for([@post, @post.comments.build]) do |f| %>
		<%= f.text_area :text %><br>
		<%= f.submit %>
	<% end %></p>
<% end %>

<div id="comments">
	<% unless @comments.empty? %>
		<h4>Comments</h4>
		<% @comments.each do |comment| %>
			<p><%= User.find_by(comment.user_id).name %> said:<br>
			<%= comment.text %>
			<% if user_signed_in? && current_user.is_admin %><br> 
				<span class="delete"><%= link_to 'Delete comment', [comment.post, comment], method: :delete, data: {confirm: 'Sure about that?' } %></span>
			<% end %></p>
		<% end %>
	<% end %>
</div>

fitblog/app/views/users/new.html.erb
<%= form_for @user, url: users_path do |f| %>
<% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prohibited the user from being created:
    <ul>
    <% @user.errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
  <% end %>
<table>
  <tr>
    <td><%= f.label :name %>: </td><td><%= f.text_field :name %></td>
  </tr>
  <tr>
    <td><%= f.label :email %>: </td><td><%= f.text_field :email %></td>
  </tr>
  <tr>
    <td><%= f.label :password %>: </td><td><%= f.password_field :password %></td>
  </tr>
  <tr>
    <td><%= f.label :password_confirmation %>: </td><td><%= f.password_field :password_confirmation %></td>
  </tr>
  <tr><td colspan="2"><%= f.submit %></td></tr>
</table>
<% end %>